
[build]
  command = "bun install && bun run build"
  functions = ".netlify/functions-internal"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  BUN_VERSION = "1.2.8"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://thehanovertheatre.org/.*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[forms]
  [forms.contact]
    name = "Contact Form"
  [forms.newsletter]
    name = "Newsletter Subscription"

